server:
  port: 8080

spring:
  profiles:
    active: "default"
  application:
    name: auth-microservice
  data:
    mongodb:
      uri: mongodb://${AUTH_DB_HOST}:${AUTH_DB_PORT}/${AUTH_DB_NAME}?authMechanism=SCRAM-SHA-256

logging:
  level:
    root: DEBUG
    org:
      springframework: DEBUG
      mongodb: DEBUG

SECRET_KEY: ${SECRET_KEY}