server:
  port: 8080

spring:
  profiles:
    active: "default"
  application:
    name: auth-microservice
  data:
    mongodb:
      uri: mongodb://${DB_USER}:${DB_PASSWORD}@${AUTH_DB_HOST}:${AUTH_DB_PORT}/${DB_NAME}?authMechanism=SCRAM-SHA-256&authSource=admin
logging:
  level:
    root: DEBUG
    org:
      springframework: DEBUG
      mongodb: DEBUG

SECRET_KEY: ${SECRET_KEY}
