server:
  port: ${APP_PORT}

spring:
  profiles:
    active: "default"
  application:
    name: auth-microservice
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    initialization-mode: always

SECRET_KEY: ${SECRET_KEY}
